#!/usr/bin/env bash
set -uex

DESTDIR=$1
shift

for arg; do
	#if [[ "$arg" =~ .*/build ]]; then continue; fi

	if [[ "$arg" =~ .*\.pkg ]]; then
		#echo "### $0: Unpacking $arg into $DESTDIR..."
		#[[ ! -d "$DESTDIR/.unpack.tmp" ]] || \
		#	rm -rf "$DESTDIR/.unpack.tmp"
		#mkdir -p "$DESTDIR/.unpack.tmp"
		tar -xf "$arg" -Izstd -C "$DESTDIR"
		#touch "$DESTDIR/.unpack.tmp"
		#mv $DESTDIR/.unpack.tmp/* ./$DESTDIR/
		#rm -d ./$DESTDIR/.unpack.tmp
	else
		if [[ ! -e "./$DESTDIR/$arg" || "$arg" -nt "./$DESTDIR/$arg" ]]; then
			echo "Copying $arg into $DESTDIR..."
			mkdir -p "$DESTDIR/$(dirname "$arg")"
			cp -a --reflink=auto "$arg" "$DESTDIR/$arg"
		fi
	fi
done
