#define NUM_APPLETS 1
#define BB_GLOBAL_CONST
#define BB_VER "1.36.1"
#define AUTOCONF_TIMESTAMP
#define _GNU_SOURCE

extern char bb_common_bufsiz1[];
#define setup_common_bufsiz() ((void)0)
enum { COMMON_BUFSIZE = 1024 };

#define CONFIG_BUSYBOX_EXEC_PATH "/proc/self/exe"
#define CONFIG_FEATURE_COPYBUF_KB 256
#define CONFIG_FEATURE_EDITING_MAX_LEN 1024
#define CONFIG_GZIP_FAST 2
#define CONFIG_UNAME_OSNAME "Linux"

#define ENABLE_ASH_ALIAS 0
#define ENABLE_ASH_BASH_COMPAT 0
#define ENABLE_ASH_CMDCMD 1
#define ENABLE_ASH_ECHO 0
#define ENABLE_ASH_GETOPTS 1
#define ENABLE_ASH_JOB_CONTROL 0
#define ENABLE_ASH_MAIL 0
#define ENABLE_ASH_PRINTF 1
#define ENABLE_ASH_SLEEP 0
#define ENABLE_ASH_TEST 1
#define ENABLE_BB_ARCH 1
#define ENABLE_BUNZIP2 0
#define ENABLE_BZCAT 0
#define ENABLE_DEBUG 0
#define ENABLE_DESKTOP 1
#define ENABLE_EGREP 0
#define ENABLE_FEATURE_ALLOW_EXEC 0
#define ENABLE_FEATURE_AWK_LIBM 0
#define ENABLE_FEATURE_BZIP2_DECOMPRESS 1
#define ENABLE_FEATURE_CLEAN_UP 0
#define ENABLE_FEATURE_CP_REFLINK 0
#define ENABLE_FEATURE_CROND_D 0
#define ENABLE_FEATURE_CUT_REGEX 0
#define ENABLE_FEATURE_EDITING 0
#define ENABLE_FEATURE_FANCY_ECHO 1
#define ENABLE_FEATURE_FIND_NOT 1
#define ENABLE_FEATURE_FIND_PAREN 1
#define ENABLE_FEATURE_FIND_PRUNE 1
#define ENABLE_FEATURE_FIND_TYPE 1
#define ENABLE_FEATURE_GZIP_DECOMPRESS 1
#define ENABLE_FEATURE_HUMAN_READABLE 0
#define ENABLE_FEATURE_LS_COLOR 0
#define ENABLE_FEATURE_LS_FILETYPES 0
#define ENABLE_FEATURE_LS_FOLLOWLINKS 0
#define ENABLE_FEATURE_LS_RECURSIVE 0
#define ENABLE_FEATURE_LS_SORTFILES 0
#define ENABLE_FEATURE_LS_TIMESTAMPS 1
#define ENABLE_FEATURE_LS_WIDTH 0
#define ENABLE_FEATURE_NON_POSIX_CP 0
#define ENABLE_FEATURE_PRESERVE_HARDLINKS 0
#define ENABLE_FEATURE_PS_ADDITIONAL_COLUMNS 0
#define ENABLE_FEATURE_SEAMLESS_BZ2 1
#define ENABLE_FEATURE_SEAMLESS_GZ 1
#define ENABLE_FEATURE_SEAMLESS_LZMA 0
#define ENABLE_FEATURE_SEAMLESS_XZ 1
#define ENABLE_FEATURE_SEAMLESS_Z 0
#define ENABLE_FEATURE_SHOW_THREADS 0
#define ENABLE_FEATURE_SH_MATH 1
#define ENABLE_FEATURE_SH_READ_FRAC 0
#define ENABLE_FEATURE_SYSLOG 0
#define ENABLE_FEATURE_TAR_AUTODETECT 1
#define ENABLE_FEATURE_TAR_CREATE 1
#define ENABLE_FEATURE_TAR_GNU_EXTENSIONS 1
#define ENABLE_FEATURE_TAR_LONG_OPTIONS 1
#define ENABLE_FEATURE_TAR_OLDGNU_COMPATIBILITY 1
#define ENABLE_FEATURE_TAR_OLDSUN_COMPATIBILITY 0
#define ENABLE_FEATURE_TOPMEM 1
#define ENABLE_FEATURE_TOP_SMP_PROCESS 0
#define ENABLE_FEATURE_TOUCH_SUSV3 1
#define ENABLE_FEATURE_TR_CLASSES 0
#define ENABLE_FEATURE_TR_EQUIV 0
#define ENABLE_FEATURE_USE_SENDFILE 0
#define ENABLE_FEATURE_VERBOSE 0
#define ENABLE_FGREP 0
#define ENABLE_FTPD 0
#define ENABLE_HUSH_PRINTF 0
#define ENABLE_HUSH_TEST 0
#define ENABLE_KILLALL 0
#define ENABLE_LOCALE_SUPPORT 1
#define ENABLE_LONG_OPTS 1
#define ENABLE_LZCAT 0
#define ENABLE_PGREP 0
#define ENABLE_PIDOF 0
#define ENABLE_PKILL 0
#define ENABLE_SELINUX 0
#define ENABLE_SESTATUS 0
#define ENABLE_TAR 1
#define ENABLE_TEST1 0
#define ENABLE_TEST2 0
#define ENABLE_UNAME 0
#define ENABLE_UNLZMA 0
#define ENABLE_ZCAT 0

#define IF_AR(...)
#define IF_ASH_ALIAS(...)
#define IF_ASH_BASH_COMPAT(...)
#define IF_ASH_EXPAND_PRMT(...)
#define IF_ASH_HELP(...)
#define IF_ASH_OPTIMIZE_FOR_SIZE(...)
#define IF_BASENAME(...)
#define IF_BUNZIP2(...)
#define IF_BZCAT(...)
#define IF_BZIP2(...) __VA_ARGS__
#define IF_CAT(...)
#define IF_CHGRP(...)
#define IF_CHMOD(...)
#define IF_CHOWN(...)
#define IF_CHROOT(...)
#define IF_CHVT(...)
#define IF_CKSUM(...)
#define IF_CLEAR(...)
#define IF_CPIO(...)
#define IF_DEALLOCVT(...)
#define IF_DESKTOP(...) __VA_ARGS__
#define IF_DPKG(...)
#define IF_DPKG_DEB(...)
#define IF_DUMPKMAP(...)
#define IF_ECHO(...) __VA_ARGS__
#define IF_EXTRA_COMPAT(...)
#define IF_FEATURE_AWK_GNU_EXTENSIONS(...)
#define IF_FEATURE_BZIP2_DECOMPRESS(...) __VA_ARGS__
#define IF_FEATURE_CATN(...)
#define IF_FEATURE_CATV(...)
#define IF_FEATURE_CP_REFLINK(...)
#define IF_FEATURE_CUT_REGEX(...)
#define IF_FEATURE_FIND_AMIN(...)
#define IF_FEATURE_FIND_ATIME(...)
#define IF_FEATURE_FIND_CMIN(...)
#define IF_FEATURE_FIND_CONTEXT(...)
#define IF_FEATURE_FIND_CTIME(...)
#define IF_FEATURE_FIND_DELETE(...)
#define IF_FEATURE_FIND_DEPTH(...)
#define IF_FEATURE_FIND_EMPTY(...)
#define IF_FEATURE_FIND_EXEC(...)
#define IF_FEATURE_FIND_EXECUTABLE(...)
#define IF_FEATURE_FIND_EXEC_PLUS(...)
#define IF_FEATURE_FIND_GROUP(...)
#define IF_FEATURE_FIND_INUM(...)
#define IF_FEATURE_FIND_LINKS(...)
#define IF_FEATURE_FIND_MAXDEPTH(...)
#define IF_FEATURE_FIND_MMIN(...)
#define IF_FEATURE_FIND_MTIME(...)
#define IF_FEATURE_FIND_NEWER(...)
#define IF_FEATURE_FIND_NOT(...) __VA_ARGS__
#define IF_FEATURE_FIND_PAREN(...) __VA_ARGS__
#define IF_FEATURE_FIND_PATH(...)
#define IF_FEATURE_FIND_PERM(...)
#define IF_FEATURE_FIND_PRINT0(...)
#define IF_FEATURE_FIND_PRUNE(...) __VA_ARGS__
#define IF_FEATURE_FIND_QUIT(...)
#define IF_FEATURE_FIND_REGEX(...)
#define IF_FEATURE_FIND_SAMEFILE(...)
#define IF_FEATURE_FIND_SIZE(...)
#define IF_FEATURE_FIND_TYPE(...) __VA_ARGS__
#define IF_FEATURE_FIND_USER(...)
#define IF_FEATURE_FIND_XDEV(...)
#define IF_FEATURE_GREP_CONTEXT(...)
#define IF_FEATURE_GZIP_DECOMPRESS(...) __VA_ARGS__
#define IF_FEATURE_HUMAN_READABLE(...)
#define IF_FEATURE_INSTALL_LONG_OPTIONS(...)
#define IF_FEATURE_LS_COLOR(...)
#define IF_FEATURE_LS_FILETYPES(...)
#define IF_FEATURE_LS_FOLLOWLINKS(...)
#define IF_FEATURE_LS_RECURSIVE(...)
#define IF_FEATURE_LS_SORTFILES(...)
#define IF_FEATURE_LS_TIMESTAMPS(...) __VA_ARGS__
#define IF_FEATURE_LS_WIDTH(...)
#define IF_FEATURE_SEAMLESS_BZ2(...) __VA_ARGS__
#define IF_FEATURE_SEAMLESS_GZ(...) __VA_ARGS__
#define IF_FEATURE_SEAMLESS_LZMA(...)
#define IF_FEATURE_SEAMLESS_XZ(...) __VA_ARGS__
#define IF_FEATURE_SEAMLESS_Z(...)
#define IF_FEATURE_SHOW_THREADS(...)
#define IF_FEATURE_SH_MATH(...) __VA_ARGS__
#define IF_FEATURE_TAR_AUTODETECT(...) __VA_ARGS__
#define IF_FEATURE_TAR_CREATE(...) __VA_ARGS__
#define IF_FEATURE_TAR_FROM(...) __VA_ARGS__
#define IF_FEATURE_TAR_LONG_OPTIONS(...) __VA_ARGS__
#define IF_FEATURE_TAR_NOPRESERVE_TIME(...) __VA_ARGS__
#define IF_FEATURE_TAR_OLDGNU_COMPATIBILITY(...) __VA_ARGS__
#define IF_FEATURE_TAR_OLDSUN_COMPATIBILITY(...)
#define IF_FEATURE_TAR_TO_COMMAND(...)
#define IF_FEATURE_TIMEZONE(...)
#define IF_FEATURE_TOUCH_SUSV3(...) __VA_ARGS__
#define IF_FEATURE_VERBOSE(...)
#define IF_FEATURE_XARGS_SUPPORT_ARGS_FILE(...)
#define IF_FEATURE_XARGS_SUPPORT_CONFIRMATION(...)
#define IF_FEATURE_XARGS_SUPPORT_PARALLEL(...)
#define IF_FEATURE_XARGS_SUPPORT_QUOTES(...)
#define IF_FEATURE_XARGS_SUPPORT_REPL_STR(...)
#define IF_FEATURE_XARGS_SUPPORT_TERMOPT(...)
#define IF_FEATURE_XARGS_SUPPORT_ZERO_TERM(...)
#define IF_FGCONSOLE(...)
#define IF_GUNZIP(...) __VA_ARGS__
#define IF_GZIP(...) __VA_ARGS__
#define IF_KBD_MODE(...)
#define IF_LOADFONT(...)
#define IF_LOADKMAP(...)
#define IF_LONG_OPTS(...) __VA_ARGS__
#define IF_LS(...) __VA_ARGS__
#define IF_LZCAT(...)
#define IF_LZMA(...)
#define IF_LZOP(...)
#define IF_LZOPCAT(...)
#define IF_NOT_ASH_OPTIMIZE_FOR_SIZE(...) __VA_ARGS__
#define IF_NOT_DESKTOP(...)
#define IF_NOT_FEATURE_FIND_MAXDEPTH(...) __VA_ARGS__
#define IF_NOT_FEATURE_TAR_CREATE(...)
#define IF_NOT_FEATURE_TOUCH_SUSV3(...)
#define IF_OPENVT(...)
#define IF_PRINTF(...) __VA_ARGS__
#define IF_RESET(...)
#define IF_RESIZE(...)
#define IF_RPM(...)
#define IF_RPM2CPIO(...)
#define IF_SELINUX(...)
#define IF_SETCONSOLE(...)
#define IF_SETFONT(...)
#define IF_SETKEYCODES(...)
#define IF_SETLOGCONS(...)
#define IF_SHELL_ASH(...) __VA_ARGS__
#define IF_SHELL_HUSH(...)
#define IF_SHOWKEY(...)
#define IF_SLEEP(...)
#define IF_TAR(...)
#define IF_UNAME(...) __VA_ARGS__
#define IF_UNCOMPRESS(...)
#define IF_UNLZMA(...)
#define IF_UNLZOP(...)
#define IF_UNXZ(...) __VA_ARGS__
#define IF_UNZIP(...)
#define IF_XZ(...)
#define IF_XZCAT(...)
#define IF_ZCAT(...)
